package com.lanou.entity;

public class Area {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.id
     *
     * @mbg.generated Tue Dec 26 10:20:04 CST 2017
     */
    private Integer id;

    /**
     *父级编码
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.parent_code
     *
     * @mbg.generated Tue Dec 26 10:20:04 CST 2017
     */
    private String parent_code;

    /**
     *地区编码
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.area_code
     *
     * @mbg.generated Tue Dec 26 10:20:04 CST 2017
     */
    private String area_code;

    /**
     *中文名称
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column area.area_name
     *
     * @mbg.generated Tue Dec 26 10:20:04 CST 2017
     */
    private String area_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.id
     *
     * @return the value of area.id
     *
     * @mbg.generated Tue Dec 26 10:20:04 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.id
     *
     * @param id the value for area.id
     *
     * @mbg.generated Tue Dec 26 10:20:04 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.parent_code
     *
     * @return the value of area.parent_code
     *
     * @mbg.generated Tue Dec 26 10:20:04 CST 2017
     */
    public String getParent_code() {
        return parent_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.parent_code
     *
     * @param parent_code the value for area.parent_code
     *
     * @mbg.generated Tue Dec 26 10:20:04 CST 2017
     */
    public void setParent_code(String parent_code) {
        this.parent_code = parent_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.area_code
     *
     * @return the value of area.area_code
     *
     * @mbg.generated Tue Dec 26 10:20:04 CST 2017
     */
    public String getArea_code() {
        return area_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.area_code
     *
     * @param area_code the value for area.area_code
     *
     * @mbg.generated Tue Dec 26 10:20:04 CST 2017
     */
    public void setArea_code(String area_code) {
        this.area_code = area_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column area.area_name
     *
     * @return the value of area.area_name
     *
     * @mbg.generated Tue Dec 26 10:20:04 CST 2017
     */
    public String getArea_name() {
        return area_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column area.area_name
     *
     * @param area_name the value for area.area_name
     *
     * @mbg.generated Tue Dec 26 10:20:04 CST 2017
     */
    public void setArea_name(String area_name) {
        this.area_name = area_name;
    }
}