package com.lanou.entity;

import java.util.Date;

public class ScrapCollector {
	
	
	private String housing_estate;
	
	

	public String getHousing_estate() {
		return housing_estate;
	}

	public void setHousing_estate(String housing_estate) {
		this.housing_estate = housing_estate;
	}
	
	private String sexval;
	

	public String getSexval() {
		return sexval;
	}

	public void setSexval(String sexval) {
		this.sexval = sexval.equals("sex_0")?"男":"女";
	}

	/**
	 * 省的名称
	 */
	private String province_name;
	/**
	 * 城市编码
	 */
	private String city_code;
	/**
	 * 省的编码
	 */
	private String province_code;

	/**
	 * 回收管理员id This field was generated by MyBatis Generator. This field corresponds
	 * to the database column scrap_collector.id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Integer id;

	/**
	 * 回收员姓名 This field was generated by MyBatis Generator. This field corresponds
	 * to the database column scrap_collector.name
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private String name;

	/**
	 * 性别，0男1女 This field was generated by MyBatis Generator. This field corresponds
	 * to the database column scrap_collector.sex
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private String sex;

	/**
	 * 身份证
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column scrap_collector.idCard
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private String idCard;

	/**
	 * 手机号 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column scrap_collector.tel
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private String tel;

	/**
	 * 房产密码 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column scrap_collector.housing_estate_code
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private String housing_estate_code;

	/**
	 * 微信openid This field was generated by MyBatis Generator. This field
	 * corresponds to the database column scrap_collector.openid
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private String openid;

	/**
	 * 收入（元） This field was generated by MyBatis Generator. This field corresponds
	 * to the database column scrap_collector.income
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Long income;

	/**
	 * 创建时间 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column scrap_collector.create_time
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Date create_time;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column scrap_collector.id
	 *
	 * @return the value of scrap_collector.id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column scrap_collector.id
	 *
	 * @param id
	 *            the value for scrap_collector.id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column scrap_collector.name
	 *
	 * @return the value of scrap_collector.name
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column scrap_collector.name
	 *
	 * @param name
	 *            the value for scrap_collector.name
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column scrap_collector.sex
	 *
	 * @return the value of scrap_collector.sex
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column scrap_collector.sex
	 *
	 * @param sex
	 *            the value for scrap_collector.sex
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column scrap_collector.idCard
	 *
	 * @return the value of scrap_collector.idCard
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public String getIdCard() {
		return idCard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column scrap_collector.idCard
	 *
	 * @param idCard
	 *            the value for scrap_collector.idCard
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setIdCard(String idCard) {
		this.idCard = idCard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column scrap_collector.tel
	 *
	 * @return the value of scrap_collector.tel
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column scrap_collector.tel
	 *
	 * @param tel
	 *            the value for scrap_collector.tel
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column scrap_collector.housing_estate_code
	 *
	 * @return the value of scrap_collector.housing_estate_code
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public String getHousing_estate_code() {
		return housing_estate_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column scrap_collector.housing_estate_code
	 *
	 * @param housing_estate_code
	 *            the value for scrap_collector.housing_estate_code
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setHousing_estate_code(String housing_estate_code) {
		this.housing_estate_code = housing_estate_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column scrap_collector.openid
	 *
	 * @return the value of scrap_collector.openid
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public String getOpenid() {
		return openid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column scrap_collector.openid
	 *
	 * @param openid
	 *            the value for scrap_collector.openid
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setOpenid(String openid) {
		this.openid = openid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column scrap_collector.income
	 *
	 * @return the value of scrap_collector.income
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Long getIncome() {
		return income;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column scrap_collector.income
	 *
	 * @param income
	 *            the value for scrap_collector.income
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setIncome(Long income) {
		this.income = income;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column scrap_collector.create_time
	 *
	 * @return the value of scrap_collector.create_time
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Date getCreate_time() {
		return create_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column scrap_collector.create_time
	 *
	 * @param create_time
	 *            the value for scrap_collector.create_time
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}

	public String getProvince_name() {
		return province_name;
	}

	public void setProvince_name(String province_name) {
		this.province_name = province_name;
	}

	public String getCity_code() {
		return city_code;
	}

	public void setCity_code(String city_code) {
		this.city_code = city_code;
	}

	public String getProvince_code() {
		return province_code;
	}

	public void setProvince_code(String province_code) {
		this.province_code = province_code;
	}

}