package com.lanou.entity;

public class Scrap {

	private Integer dictId;

	public Integer getDictId() {
		return dictId;
	}

	public void setDictId(Integer dictId) {
		this.dictId = dictId;
	}

	/**
	 * 废品id This field was generated by MyBatis Generator. This field corresponds to
	 * the database column scrap.id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Integer id;

	/**
	 * 废品编码 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column scrap.scrap_code
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private String scrap_code;

	/**
	 * 废品名称 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column scrap.scrap_name
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private String scrap_name;

	/**
	 * 废品类别名称
	 */
	private String categoryName;

	/**
	 * 类别，（数据字典可查） This field was generated by MyBatis Generator. This field
	 * corresponds to the database column scrap.category
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private String category;

	/**
	 * 回收单位 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column scrap.unit
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private String unit;

	/**
	 * 价格（元/千克） This field was generated by MyBatis Generator. This field
	 * corresponds to the database column scrap.price
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Integer price;

	/**
	 * 积分（分/千克） This field was generated by MyBatis Generator. This field
	 * corresponds to the database column scrap.score
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Integer score;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column scrap.id
	 *
	 * @return the value of scrap.id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column scrap.id
	 *
	 * @param id
	 *            the value for scrap.id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column scrap.scrap_code
	 *
	 * @return the value of scrap.scrap_code
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public String getScrap_code() {
		return scrap_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column scrap.scrap_code
	 *
	 * @param scrap_code
	 *            the value for scrap.scrap_code
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setScrap_code(String scrap_code) {
		this.scrap_code = scrap_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column scrap.scrap_name
	 *
	 * @return the value of scrap.scrap_name
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public String getScrap_name() {
		return scrap_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column scrap.scrap_name
	 *
	 * @param scrap_name
	 *            the value for scrap.scrap_name
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setScrap_name(String scrap_name) {
		this.scrap_name = scrap_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column scrap.category
	 *
	 * @return the value of scrap.category
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public String getCategory() {
		return category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column scrap.category
	 *
	 * @param category
	 *            the value for scrap.category
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setCategory(String category) {
		this.category = category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column scrap.unit
	 *
	 * @return the value of scrap.unit
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public String getUnit() {
		return unit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column scrap.unit
	 *
	 * @param unit
	 *            the value for scrap.unit
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setUnit(String unit) {
		this.unit = unit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column scrap.price
	 *
	 * @return the value of scrap.price
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Integer getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column scrap.price
	 *
	 * @param price
	 *            the value for scrap.price
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setPrice(Integer price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column scrap.score
	 *
	 * @return the value of scrap.score
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Integer getScore() {
		return score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column scrap.score
	 *
	 * @param score
	 *            the value for scrap.score
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setScore(Integer score) {
		this.score = score;
	}

	public String getCategoryName() {
		return categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

}