package com.lanou.entity;

import java.util.Date;

public class SysDepartment {
	/**
	 * 上级机构id This field was generated by MyBatis Generator. This field corresponds
	 * to the database column sys_department.id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Integer id;

	/**
	 * 上级机构 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_department.parent_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Integer parent_id;

	/**
	 * 部门/11111 This field was generated by MyBatis Generator. This field
	 * corresponds to the database column sys_department.name
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private String name;

	/**
	 * 机构编码 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_department.code
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private String code;

	/**
	 * 序号 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_department.sort
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Integer sort;

	/**
	 * 联系人 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_department.linkman
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private String linkman;

	/**
	 * 联系人电话 This field was generated by MyBatis Generator. This field corresponds
	 * to the database column sys_department.linkman_no
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private String linkman_no;

	/**
	 * 机构描述 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_department.remark
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private String remark;

	/**
	 * 更新时间 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_department.update_time
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Date update_time;

	/**
	 * 更新者 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_department.update_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Integer update_id;

	/**
	 * 创建时间 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_department.create_time
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Date create_time;

	/**
	 * 创建者 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_department.create_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Integer create_id;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_department.id
	 *
	 * @return the value of sys_department.id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_department.id
	 *
	 * @param id
	 *            the value for sys_department.id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_department.parent_id
	 *
	 * @return the value of sys_department.parent_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Integer getParent_id() {
		return parent_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_department.parent_id
	 *
	 * @param parent_id
	 *            the value for sys_department.parent_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setParent_id(Integer parent_id) {
		this.parent_id = parent_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_department.name
	 *
	 * @return the value of sys_department.name
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_department.name
	 *
	 * @param name
	 *            the value for sys_department.name
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_department.code
	 *
	 * @return the value of sys_department.code
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_department.code
	 *
	 * @param code
	 *            the value for sys_department.code
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_department.sort
	 *
	 * @return the value of sys_department.sort
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Integer getSort() {
		return sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_department.sort
	 *
	 * @param sort
	 *            the value for sys_department.sort
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setSort(Integer sort) {
		this.sort = sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_department.linkman
	 *
	 * @return the value of sys_department.linkman
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public String getLinkman() {
		return linkman;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_department.linkman
	 *
	 * @param linkman
	 *            the value for sys_department.linkman
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setLinkman(String linkman) {
		this.linkman = linkman;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_department.linkman_no
	 *
	 * @return the value of sys_department.linkman_no
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public String getLinkman_no() {
		return linkman_no;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_department.linkman_no
	 *
	 * @param linkman_no
	 *            the value for sys_department.linkman_no
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setLinkman_no(String linkman_no) {
		this.linkman_no = linkman_no;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_department.remark
	 *
	 * @return the value of sys_department.remark
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_department.remark
	 *
	 * @param remark
	 *            the value for sys_department.remark
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_department.update_time
	 *
	 * @return the value of sys_department.update_time
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Date getUpdate_time() {
		return update_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_department.update_time
	 *
	 * @param update_time
	 *            the value for sys_department.update_time
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setUpdate_time(Date update_time) {
		this.update_time = update_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_department.update_id
	 *
	 * @return the value of sys_department.update_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Integer getUpdate_id() {
		return update_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_department.update_id
	 *
	 * @param update_id
	 *            the value for sys_department.update_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setUpdate_id(Integer update_id) {
		this.update_id = update_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_department.create_time
	 *
	 * @return the value of sys_department.create_time
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Date getCreate_time() {
		return create_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_department.create_time
	 *
	 * @param create_time
	 *            the value for sys_department.create_time
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_department.create_id
	 *
	 * @return the value of sys_department.create_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Integer getCreate_id() {
		return create_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_department.create_id
	 *
	 * @param create_id
	 *            the value for sys_department.create_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setCreate_id(Integer create_id) {
		this.create_id = create_id;
	}
}