package com.lanou.entity;

public class SysDict {
	/**
	 * 数据字典id This field was generated by MyBatis Generator. This field corresponds
	 * to the database column sys_dict.id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Integer id;

	/**
	 * 字典名称 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_dict.dict_tabname
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private String dict_tabname;

	/**
	 * 字典类型 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_dict.dict_colname
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private String dict_colname;

	/**
	 * 字典备注 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_dict.dict_option
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private String dict_option;

	/**
	 * 字典文本 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_dict.dict_text
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private String dict_text;

	/**
	 * 字典分类 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_dict.dict_sort
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Integer dict_sort;

	/**
	 * 字典名称 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_dict.dict_name
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private String dict_name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_dict.id
	 *
	 * @return the value of sys_dict.id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_dict.id
	 *
	 * @param id
	 *            the value for sys_dict.id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_dict.dict_tabname
	 *
	 * @return the value of sys_dict.dict_tabname
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public String getDict_tabname() {
		return dict_tabname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_dict.dict_tabname
	 *
	 * @param dict_tabname
	 *            the value for sys_dict.dict_tabname
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setDict_tabname(String dict_tabname) {
		this.dict_tabname = dict_tabname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_dict.dict_colname
	 *
	 * @return the value of sys_dict.dict_colname
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public String getDict_colname() {
		return dict_colname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_dict.dict_colname
	 *
	 * @param dict_colname
	 *            the value for sys_dict.dict_colname
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setDict_colname(String dict_colname) {
		this.dict_colname = dict_colname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_dict.dict_option
	 *
	 * @return the value of sys_dict.dict_option
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public String getDict_option() {
		return dict_option;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_dict.dict_option
	 *
	 * @param dict_option
	 *            the value for sys_dict.dict_option
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setDict_option(String dict_option) {
		this.dict_option = dict_option;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_dict.dict_text
	 *
	 * @return the value of sys_dict.dict_text
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public String getDict_text() {
		return dict_text;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_dict.dict_text
	 *
	 * @param dict_text
	 *            the value for sys_dict.dict_text
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setDict_text(String dict_text) {
		this.dict_text = dict_text;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_dict.dict_sort
	 *
	 * @return the value of sys_dict.dict_sort
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Integer getDict_sort() {
		return dict_sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_dict.dict_sort
	 *
	 * @param dict_sort
	 *            the value for sys_dict.dict_sort
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setDict_sort(Integer dict_sort) {
		this.dict_sort = dict_sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_dict.dict_name
	 *
	 * @return the value of sys_dict.dict_name
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public String getDict_name() {
		return dict_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_dict.dict_name
	 *
	 * @param dict_name
	 *            the value for sys_dict.dict_name
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setDict_name(String dict_name) {
		this.dict_name = dict_name;
	}
}