package com.lanou.entity;

import java.util.Date;

public class SysDictDetail {
	/**
	 * 数据字典详细信息 This field was generated by MyBatis Generator. This field
	 * corresponds to the database column sys_dict_detail.detail_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Integer detail_id;

	/**
	 * 数据字典类型 This field was generated by MyBatis Generator. This field corresponds
	 * to the database column sys_dict_detail.dict_type
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private String dict_type;

	/**
	 * 详述名称 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_dict_detail.detail_name
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private String detail_name;

	/**
	 * 详述代码 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_dict_detail.detail_code
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private String detail_code;

	/**
	 * 详述排序号 This field was generated by MyBatis Generator. This field corresponds
	 * to the database column sys_dict_detail.detail_sort
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private String detail_sort;

	/**
	 * 详述类型 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_dict_detail.detail_type
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private String detail_type;

	/**
	 * 详述状态 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_dict_detail.detail_state
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private String detail_state;

	/**
	 * 详述内容 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_dict_detail.detail_content
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private String detail_content;

	/**
	 * 详述备注 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_dict_detail.detail_remark
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private String detail_remark;

	/**
	 * 创建时剑 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_dict_detail.create_time
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Date create_time;

	/**
	 * 创建者 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_dict_detail.create_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Integer create_id;

	/**
	 * 更新时间 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_dict_detail.update_time
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Date update_time;

	/**
	 * 更新的人 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_dict_detail.update_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Integer update_id;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_dict_detail.detail_id
	 *
	 * @return the value of sys_dict_detail.detail_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Integer getDetail_id() {
		return detail_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_dict_detail.detail_id
	 *
	 * @param detail_id
	 *            the value for sys_dict_detail.detail_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setDetail_id(Integer detail_id) {
		this.detail_id = detail_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_dict_detail.dict_type
	 *
	 * @return the value of sys_dict_detail.dict_type
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public String getDict_type() {
		return dict_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_dict_detail.dict_type
	 *
	 * @param dict_type
	 *            the value for sys_dict_detail.dict_type
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setDict_type(String dict_type) {
		this.dict_type = dict_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_dict_detail.detail_name
	 *
	 * @return the value of sys_dict_detail.detail_name
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public String getDetail_name() {
		return detail_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_dict_detail.detail_name
	 *
	 * @param detail_name
	 *            the value for sys_dict_detail.detail_name
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setDetail_name(String detail_name) {
		this.detail_name = detail_name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_dict_detail.detail_code
	 *
	 * @return the value of sys_dict_detail.detail_code
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public String getDetail_code() {
		return detail_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_dict_detail.detail_code
	 *
	 * @param detail_code
	 *            the value for sys_dict_detail.detail_code
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setDetail_code(String detail_code) {
		this.detail_code = detail_code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_dict_detail.detail_sort
	 *
	 * @return the value of sys_dict_detail.detail_sort
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public String getDetail_sort() {
		return detail_sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_dict_detail.detail_sort
	 *
	 * @param detail_sort
	 *            the value for sys_dict_detail.detail_sort
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setDetail_sort(String detail_sort) {
		this.detail_sort = detail_sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_dict_detail.detail_type
	 *
	 * @return the value of sys_dict_detail.detail_type
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public String getDetail_type() {
		return detail_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_dict_detail.detail_type
	 *
	 * @param detail_type
	 *            the value for sys_dict_detail.detail_type
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setDetail_type(String detail_type) {
		this.detail_type = detail_type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_dict_detail.detail_state
	 *
	 * @return the value of sys_dict_detail.detail_state
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public String getDetail_state() {
		return detail_state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_dict_detail.detail_state
	 *
	 * @param detail_state
	 *            the value for sys_dict_detail.detail_state
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setDetail_state(String detail_state) {
		this.detail_state = detail_state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_dict_detail.detail_content
	 *
	 * @return the value of sys_dict_detail.detail_content
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public String getDetail_content() {
		return detail_content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_dict_detail.detail_content
	 *
	 * @param detail_content
	 *            the value for sys_dict_detail.detail_content
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setDetail_content(String detail_content) {
		this.detail_content = detail_content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_dict_detail.detail_remark
	 *
	 * @return the value of sys_dict_detail.detail_remark
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public String getDetail_remark() {
		return detail_remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_dict_detail.detail_remark
	 *
	 * @param detail_remark
	 *            the value for sys_dict_detail.detail_remark
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setDetail_remark(String detail_remark) {
		this.detail_remark = detail_remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_dict_detail.create_time
	 *
	 * @return the value of sys_dict_detail.create_time
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Date getCreate_time() {
		return create_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_dict_detail.create_time
	 *
	 * @param create_time
	 *            the value for sys_dict_detail.create_time
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_dict_detail.create_id
	 *
	 * @return the value of sys_dict_detail.create_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Integer getCreate_id() {
		return create_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_dict_detail.create_id
	 *
	 * @param create_id
	 *            the value for sys_dict_detail.create_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setCreate_id(Integer create_id) {
		this.create_id = create_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_dict_detail.update_time
	 *
	 * @return the value of sys_dict_detail.update_time
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Date getUpdate_time() {
		return update_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_dict_detail.update_time
	 *
	 * @param update_time
	 *            the value for sys_dict_detail.update_time
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setUpdate_time(Date update_time) {
		this.update_time = update_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_dict_detail.update_id
	 *
	 * @return the value of sys_dict_detail.update_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Integer getUpdate_id() {
		return update_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_dict_detail.update_id
	 *
	 * @param update_id
	 *            the value for sys_dict_detail.update_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setUpdate_id(Integer update_id) {
		this.update_id = update_id;
	}
}