package com.lanou.entity;

import java.util.Date;

public class SysMenu {
	/**
	 * 父级名称
	 */
	private String parentName;
	/**
	 * 菜单id This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_menu.id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Integer id;

	/**
	 * 父id This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_menu.parentId
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Integer parentId;

	/**
	 * 图标 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_menu.icon
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private String icon;

	/**
	 * 名称 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_menu.name
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private String name;

	/**
	 * 菜单key This field was generated by MyBatis Generator. This field corresponds
	 * to the database column sys_menu.urlkey
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private String urlkey;

	/**
	 * 链接地址 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_menu.url
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private String url;

	/**
	 * 状态 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_menu.status
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Integer status;

	/**
	 * 类型 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_menu.type
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Integer type;

	/**
	 * 排序 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_menu.sort
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Integer sort;

	/**
	 * 级别 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_menu.level
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Integer level;

	/**
	 * 创建时剑 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_menu.create_time
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Date create_time;

	/**
	 * 创建的人 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_menu.create_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Integer create_id;

	/**
	 * 更新时间 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_menu.update_time
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Date update_time;

	/**
	 * 更新的人 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_menu.update_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Integer update_id;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu.id
	 *
	 * @return the value of sys_menu.id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu.id
	 *
	 * @param id
	 *            the value for sys_menu.id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu.parentId
	 *
	 * @return the value of sys_menu.parentId
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Integer getparentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu.parentId
	 *
	 * @param parentId
	 *            the value for sys_menu.parentId
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setparentId(Integer parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu.icon
	 *
	 * @return the value of sys_menu.icon
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public String getIcon() {
		return icon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu.icon
	 *
	 * @param icon
	 *            the value for sys_menu.icon
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setIcon(String icon) {
		this.icon = icon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu.name
	 *
	 * @return the value of sys_menu.name
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu.name
	 *
	 * @param name
	 *            the value for sys_menu.name
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu.urlkey
	 *
	 * @return the value of sys_menu.urlkey
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public String getUrlkey() {
		return urlkey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu.urlkey
	 *
	 * @param urlkey
	 *            the value for sys_menu.urlkey
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setUrlkey(String urlkey) {
		this.urlkey = urlkey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu.url
	 *
	 * @return the value of sys_menu.url
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu.url
	 *
	 * @param url
	 *            the value for sys_menu.url
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu.status
	 *
	 * @return the value of sys_menu.status
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu.status
	 *
	 * @param status
	 *            the value for sys_menu.status
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu.type
	 *
	 * @return the value of sys_menu.type
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu.type
	 *
	 * @param type
	 *            the value for sys_menu.type
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu.sort
	 *
	 * @return the value of sys_menu.sort
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Integer getSort() {
		return sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu.sort
	 *
	 * @param sort
	 *            the value for sys_menu.sort
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setSort(Integer sort) {
		this.sort = sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu.level
	 *
	 * @return the value of sys_menu.level
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Integer getLevel() {
		return level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu.level
	 *
	 * @param level
	 *            the value for sys_menu.level
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setLevel(Integer level) {
		this.level = level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu.create_time
	 *
	 * @return the value of sys_menu.create_time
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Date getCreate_time() {
		return create_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu.create_time
	 *
	 * @param create_time
	 *            the value for sys_menu.create_time
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu.create_id
	 *
	 * @return the value of sys_menu.create_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Integer getCreate_id() {
		return create_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu.create_id
	 *
	 * @param create_id
	 *            the value for sys_menu.create_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setCreate_id(Integer create_id) {
		this.create_id = create_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu.update_time
	 *
	 * @return the value of sys_menu.update_time
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Date getUpdate_time() {
		return update_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu.update_time
	 *
	 * @param update_time
	 *            the value for sys_menu.update_time
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setUpdate_time(Date update_time) {
		this.update_time = update_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_menu.update_id
	 *
	 * @return the value of sys_menu.update_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Integer getUpdate_id() {
		return update_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_menu.update_id
	 *
	 * @param update_id
	 *            the value for sys_menu.update_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setUpdate_id(Integer update_id) {
		this.update_id = update_id;
	}

	public String getParentName() {
		return parentName;
	}

	public void setParentName(String parentName) {
		this.parentName = parentName;
	}

}