package com.lanou.entity;

public class SysRoleMenu {
	/**
	 * 角色菜单id
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_role_menu.id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Integer id;

	/**
	 * 角色id This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_role_menu.roleid
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Integer roleid;

	/**
	 * 菜单id This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_role_menu.menuid
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Integer menuid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_role_menu.id
	 *
	 * @return the value of sys_role_menu.id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_role_menu.id
	 *
	 * @param id
	 *            the value for sys_role_menu.id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_role_menu.roleid
	 *
	 * @return the value of sys_role_menu.roleid
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Integer getRoleid() {
		return roleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_role_menu.roleid
	 *
	 * @param roleid
	 *            the value for sys_role_menu.roleid
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setRoleid(Integer roleid) {
		this.roleid = roleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_role_menu.menuid
	 *
	 * @return the value of sys_role_menu.menuid
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Integer getMenuid() {
		return menuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_role_menu.menuid
	 *
	 * @param menuid
	 *            the value for sys_role_menu.menuid
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setMenuid(Integer menuid) {
		this.menuid = menuid;
	}
}