package com.lanou.entity;

import java.util.Date;

public class SysRole {
	/**
	 * 角色id This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_role.id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Integer id;

	/**
	 * 名称 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_role.name
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private String name;

	/**
	 * 状态1显示2隐藏 This field was generated by MyBatis Generator. This field
	 * corresponds to the database column sys_role.status
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Integer status;

	/**
	 * 排序 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_role.sort
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Integer sort;

	/**
	 * 创建时间 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_role.create_time
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Date create_time;

	/**
	 * 创建者 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_role.create_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Integer create_id;

	/**
	 * 更新时间 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_role.update_time
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Date update_time;

	/**
	 * 更新人 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_role.update_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Integer update_id;

	/**
	 * 说明 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_role.remark
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_role.id
	 *
	 * @return the value of sys_role.id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_role.id
	 *
	 * @param id
	 *            the value for sys_role.id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_role.name
	 *
	 * @return the value of sys_role.name
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_role.name
	 *
	 * @param name
	 *            the value for sys_role.name
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_role.status
	 *
	 * @return the value of sys_role.status
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_role.status
	 *
	 * @param status
	 *            the value for sys_role.status
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_role.sort
	 *
	 * @return the value of sys_role.sort
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Integer getSort() {
		return sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_role.sort
	 *
	 * @param sort
	 *            the value for sys_role.sort
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setSort(Integer sort) {
		this.sort = sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_role.create_time
	 *
	 * @return the value of sys_role.create_time
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Date getCreate_time() {
		return create_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_role.create_time
	 *
	 * @param create_time
	 *            the value for sys_role.create_time
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_role.create_id
	 *
	 * @return the value of sys_role.create_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Integer getCreate_id() {
		return create_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_role.create_id
	 *
	 * @param create_id
	 *            the value for sys_role.create_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setCreate_id(Integer create_id) {
		this.create_id = create_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_role.update_time
	 *
	 * @return the value of sys_role.update_time
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Date getUpdate_time() {
		return update_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_role.update_time
	 *
	 * @param update_time
	 *            the value for sys_role.update_time
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setUpdate_time(Date update_time) {
		this.update_time = update_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_role.update_id
	 *
	 * @return the value of sys_role.update_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Integer getUpdate_id() {
		return update_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_role.update_id
	 *
	 * @param update_id
	 *            the value for sys_role.update_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setUpdate_id(Integer update_id) {
		this.update_id = update_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_role.remark
	 *
	 * @return the value of sys_role.remark
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_role.remark
	 *
	 * @param remark
	 *            the value for sys_role.remark
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}
}