package com.lanou.entity;

import java.util.Date;

public class SysUser {
	/**
	 * 角色姓名
	 */
	private String roleName;
	/**
	 * 用户id This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_user.id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Integer id;

	/**
	 * 用户名 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_user.username
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private String username;

	/**
	 * 密码 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_user.password
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private String password;

	/**
	 * 真实姓名 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_user.realname
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private String realname;

	/**
	 * 角色id This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_user.role_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Integer roleId;

	/**
	 * 用户种类 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_user.usertype
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Integer usertype;

	/**
	 * 状态 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_user.state
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Integer state;

	/**
	 * 第三方id
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sys_user.third_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private String third_id;

	/**
	 * 结束时间 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_user.end_time
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Date end_time;

	/**
	 * 邮件 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_user.email
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private String email;

	/**
	 * 手机号 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_user.tel
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private String tel;

	/**
	 * 地址 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_user.address
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private String address;

	/**
	 * 标题地址 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_user.title_url
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private String title_url;

	/**
	 * 说明 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_user.remark
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private String remark;

	/**
	 * 主题 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_user.theme
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private String theme;

	/**
	 * 后台选择站点id This field was generated by MyBatis Generator. This field
	 * corresponds to the database column sys_user.back_site_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Integer back_site_id;

	/**
	 * 创建站点id This field was generated by MyBatis Generator. This field corresponds
	 * to the database column sys_user.create_site_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Integer create_site_id;

	/**
	 * 创建时间 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_user.create_time
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Date create_time;

	/**
	 * 创建的人 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_user.create_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Integer create_id;

	/**
	 * 更新时间 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_user.update_time
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Date update_time;

	/**
	 * 更新的人 This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_user.update_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	private Integer update_id;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_user.id
	 *
	 * @return the value of sys_user.id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_user.id
	 *
	 * @param id
	 *            the value for sys_user.id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_user.username
	 *
	 * @return the value of sys_user.username
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_user.username
	 *
	 * @param username
	 *            the value for sys_user.username
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_user.password
	 *
	 * @return the value of sys_user.password
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_user.password
	 *
	 * @param password
	 *            the value for sys_user.password
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_user.realname
	 *
	 * @return the value of sys_user.realname
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public String getRealname() {
		return realname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_user.realname
	 *
	 * @param realname
	 *            the value for sys_user.realname
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setRealname(String realname) {
		this.realname = realname;
	}

	public Integer getRoleId() {
		return roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_user.usertype
	 *
	 * @return the value of sys_user.usertype
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Integer getUsertype() {
		return usertype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_user.usertype
	 *
	 * @param usertype
	 *            the value for sys_user.usertype
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setUsertype(Integer usertype) {
		this.usertype = usertype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_user.state
	 *
	 * @return the value of sys_user.state
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_user.state
	 *
	 * @param state
	 *            the value for sys_user.state
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_user.third_id
	 *
	 * @return the value of sys_user.third_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public String getThird_id() {
		return third_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_user.third_id
	 *
	 * @param third_id
	 *            the value for sys_user.third_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setThird_id(String third_id) {
		this.third_id = third_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_user.end_time
	 *
	 * @return the value of sys_user.end_time
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Date getEnd_time() {
		return end_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_user.end_time
	 *
	 * @param end_time
	 *            the value for sys_user.end_time
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setEnd_time(Date end_time) {
		this.end_time = end_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_user.email
	 *
	 * @return the value of sys_user.email
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_user.email
	 *
	 * @param email
	 *            the value for sys_user.email
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_user.tel
	 *
	 * @return the value of sys_user.tel
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_user.tel
	 *
	 * @param tel
	 *            the value for sys_user.tel
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_user.address
	 *
	 * @return the value of sys_user.address
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_user.address
	 *
	 * @param address
	 *            the value for sys_user.address
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_user.title_url
	 *
	 * @return the value of sys_user.title_url
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public String getTitle_url() {
		return title_url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_user.title_url
	 *
	 * @param title_url
	 *            the value for sys_user.title_url
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setTitle_url(String title_url) {
		this.title_url = title_url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_user.remark
	 *
	 * @return the value of sys_user.remark
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_user.remark
	 *
	 * @param remark
	 *            the value for sys_user.remark
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_user.theme
	 *
	 * @return the value of sys_user.theme
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public String getTheme() {
		return theme;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_user.theme
	 *
	 * @param theme
	 *            the value for sys_user.theme
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setTheme(String theme) {
		this.theme = theme;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_user.back_site_id
	 *
	 * @return the value of sys_user.back_site_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Integer getBack_site_id() {
		return back_site_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_user.back_site_id
	 *
	 * @param back_site_id
	 *            the value for sys_user.back_site_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setBack_site_id(Integer back_site_id) {
		this.back_site_id = back_site_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_user.create_site_id
	 *
	 * @return the value of sys_user.create_site_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Integer getCreate_site_id() {
		return create_site_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_user.create_site_id
	 *
	 * @param create_site_id
	 *            the value for sys_user.create_site_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setCreate_site_id(Integer create_site_id) {
		this.create_site_id = create_site_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_user.create_time
	 *
	 * @return the value of sys_user.create_time
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Date getCreate_time() {
		return create_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_user.create_time
	 *
	 * @param create_time
	 *            the value for sys_user.create_time
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setCreate_time(Date create_time) {
		this.create_time = create_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_user.create_id
	 *
	 * @return the value of sys_user.create_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Integer getCreate_id() {
		return create_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_user.create_id
	 *
	 * @param create_id
	 *            the value for sys_user.create_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setCreate_id(Integer create_id) {
		this.create_id = create_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_user.update_time
	 *
	 * @return the value of sys_user.update_time
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Date getUpdate_time() {
		return update_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_user.update_time
	 *
	 * @param update_time
	 *            the value for sys_user.update_time
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setUpdate_time(Date update_time) {
		this.update_time = update_time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sys_user.update_id
	 *
	 * @return the value of sys_user.update_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public Integer getUpdate_id() {
		return update_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sys_user.update_id
	 *
	 * @param update_id
	 *            the value for sys_user.update_id
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	public void setUpdate_id(Integer update_id) {
		this.update_id = update_id;
	}

	public String getRoleName() {
		return roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

}