package com.lanou.mapper;

import java.util.List;
import java.util.Map;

import org.mybatis.spring.annotation.MapperScan;
import org.springframework.web.bind.annotation.RequestParam;

import com.lanou.bean.HouseEstateBean;
import com.lanou.entity.HouseEstate;

@MapperScan
public interface HouseEstateMapper {
	/**
	 * 根据小区id删除小区信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table housing_estate
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * 新增小区信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table housing_estate
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	int insert(HouseEstate record);

	/**
	 * 动态增加小区信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table housing_estate
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	int insertSelective(HouseEstate record);

	/**
	 * 根据小区id查询小区信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table housing_estate
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	HouseEstate selectByPrimaryKey(Integer id);

	/**
	 * 动态修改小区信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table housing_estate
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	int updateByPrimaryKeySelective(HouseEstate record);

	/**
	 * 修改小区信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table housing_estate
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	int updateByPrimaryKey(HouseEstate record);

	/**
	 * 小区分页列表
	 * 
	 * @param map
	 * @return
	 */
	List<HouseEstateBean> selectAll(Map<String, Object> map);

	/**
	 * 总条数
	 * 
	 * @param map
	 * @return
	 */
	int selectCount(Map<String, Object> map);

	// 王刘鹏修改
	/**
	 * 查询所有小区信息
	 * 
	 * @return
	 */
	List<HouseEstate> selectAllHouse(Integer cityCode);

}