package com.lanou.mapper;

import java.util.List;
import java.util.Map;

import org.mybatis.spring.annotation.MapperScan;

import com.lanou.bean.OwnerBean;
import com.lanou.entity.Owner;

@MapperScan
public interface OwnerMapper {
	/**
	 * 根据id删除业主信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table owner
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * 新增业主信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table owner
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	int insert(Owner record);

	/**
	 * 动态新增业主信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table owner
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	int insertSelective(Owner record);

	/**
	 * 根据业主id查询业主信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table owner
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	Owner selectByPrimaryKey(Integer id);

	/**
	 * 动态修改业主信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table owner
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	int updateByPrimaryKeySelective(Owner record);

	/**
	 * 修改业主信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table owner
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	int updateByPrimaryKey(Owner record);

	/**
	 * 查询所有
	 * 
	 * @return
	 */
	List<OwnerBean> selectAll(Map<String, Object> map);

	/**
	 * 查询总条数
	 * 
	 * @return
	 */
	int selectCount(Map<String, Object> map);
}