package com.lanou.mapper;

import java.util.List;
import java.util.Map;

import org.mybatis.spring.annotation.MapperScan;

import com.lanou.bean.ReclBean;
import com.lanou.entity.ReclOrder;

@MapperScan
public interface ReclOrderMapper {
	/**
	 * 根据废品订单id删除订单信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table reclamation_order
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * 新增废品订单信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table reclamation_order
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	int insert(ReclOrder record);

	/**
	 * 动态增加废品订单信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table reclamation_order
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	int insertSelective(ReclOrder record);

	/**
	 * 根据废品订单id查询废品订单信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table reclamation_order
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	ReclOrder selectByPrimaryKey(Integer id);

	/**
	 * 动态修改废品订单信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table reclamation_order
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	int updateByPrimaryKeySelective(ReclOrder record);

	/**
	 * 修改废品订单信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table reclamation_order
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	int updateByPrimaryKey(ReclOrder record);

	/**
	 * 查询所有废品订单管理信息
	 * 
	 * @return
	 */
	List<ReclBean> selectAll(Map<String, Object> map);

	/**
	 * 查询总的条数
	 * 
	 * @return
	 */
	int selectPageCount(Map<String, Object> map);
}