package com.lanou.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.annotation.MapperScan;

import com.lanou.entity.SysDict;

@MapperScan
public interface SysDictMapper {
	/**
	 * 根据字典id删除字典信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_dict
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * 新增字典信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_dict
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	int insert(SysDict record);

	/**
	 * 动态新增字典信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_dict
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	int insertSelective(SysDict record);

	/**
	 * 根据字典id查询字典信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_dict
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	SysDict selectByPrimaryKey(Integer id);

	/**
	 * 动态修改字典信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_dict
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	int updateByPrimaryKeySelective(SysDict record);

	/**
	 * 修改字典信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_dict
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	int updateByPrimaryKey(SysDict record);

	/**
	 * 数字字典分页显示
	 * 
	 * @return
	 */
	List<SysDict> selectPageList(Map<String, Object> map);

	/**
	 * 总条数
	 * 
	 * @param map
	 * @return
	 */
	int selectCount(Map<String, Object> map);

	/**
	 * 查询所有信息
	 * 
	 * @return
	 */
	List<SysDict> selectAll(@Param("dict_tabname") String dict_tabname);
}