package com.lanou.mapper;

import org.mybatis.spring.annotation.MapperScan;

import com.lanou.entity.SysDepartment;
@MapperScan
public interface SysDepartmentMapper {
    /**
     *根据上级机构id删除上级机构信息
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_department
     *
     * @mbg.generated Tue Dec 26 10:20:04 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**新增上级机构信息
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_department
     *
     * @mbg.generated Tue Dec 26 10:20:04 CST 2017
     */
    int insert(SysDepartment record);

    /**动态新增上级结构信息
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_department
     *
     * @mbg.generated Tue Dec 26 10:20:04 CST 2017
     */
    int insertSelective(SysDepartment record);

    /**根据上级结构id查询上级结构信息
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_department
     *
     * @mbg.generated Tue Dec 26 10:20:04 CST 2017
     */
    SysDepartment selectByPrimaryKey(Integer id);

    /**动态修改上级结构信息
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_department
     *
     * @mbg.generated Tue Dec 26 10:20:04 CST 2017
     */
    int updateByPrimaryKeySelective(SysDepartment record);

    /**修改上级结构信息
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_department
     *
     * @mbg.generated Tue Dec 26 10:20:04 CST 2017
     */
    int updateByPrimaryKey(SysDepartment record);
}