package com.lanou.mapper;

import java.util.List;
import java.util.Map;

import org.mybatis.spring.annotation.MapperScan;

import com.lanou.bean.MenuBean;
import com.lanou.entity.SysMenu;

@MapperScan
public interface SysMenuMapper {
	/**
	 * 根据菜单id删除菜单信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_menu
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	int deleteByPrimaryKey(int id);

	/**
	 * 新增菜单信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_menu
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	int insertSelective(SysMenu record);

	/**
	 * 根据菜单id查询菜单信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_menu
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	SysMenu selectByPrimaryKey(Integer id);

	/**
	 * 动态修改菜单信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_menu
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	int updateByPrimaryKeySelective(SysMenu record);

	/**
	 * 修改菜单信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_menu
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	int updateByPrimaryKey(SysMenu record);

	/**
	 * 查询菜单管理的所有数据
	 * 
	 * @return
	 */
	public List<MenuBean> selectAll(Map<String, Object> map);

	/**
	 * 总条数
	 * 
	 * @param map
	 * @return
	 */
	public int selectCount(Map<String, Object> map);

	/**
	 * 添加中的下拉选
	 * 
	 * @return
	 */
	public List<SysMenu> selectMenuAll();
}