package com.lanou.mapper;

import java.util.List;
import java.util.Map;

import org.mybatis.spring.annotation.MapperScan;

import com.lanou.bean.RoleBean;
import com.lanou.entity.SysRole;

//标识这个类为持久化类
@MapperScan
public interface SysRoleMapper {
	/**
	 * 根据角色id删除角色信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_role
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_role
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	/**
	 * 添加角色
	 * 
	 * @param record
	 * @return
	 */
	int insert(SysRole record);

	/**
	 * 动态添加角色信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_role
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	int insertSelective(SysRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sys_role
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	/**
	 * 根据id查询角色 因为前段页面需要id判断增删改 role_add.js
	 * 
	 * @param id
	 * @return
	 */
	SysRole selectByPrimaryKey(Integer id);

	/**
	 * 动态修改角色信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_role
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	int updateByPrimaryKeySelective(SysRole record);

	/**
	 * 以一个大文件的形式修改角色信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_role
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(SysRole record);

	/**
	 * 修改角色信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_role
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	int updateByPrimaryKey(SysRole record);
	// ********************************************************************************

	/**
	 * 查询角色管理展示数据 一页显示的内容，封装分页传过来的多个值，所以用map集合
	 * 
	 * @return
	 */
	public List<RoleBean> selectAll(Map<String, Object> map);

	/**
	 * 总记录条数
	 * 
	 * @param map
	 * @return
	 */
	int selectPageCount(Map<String, Object> map);

	/**
	 * 删除角色
	 * 
	 * @param id
	 * @return
	 */
	int delete(Integer id);

	/**
	 * 修改角色
	 * 
	 * @param record
	 * @return
	 */
	int update(SysRole record);

	/**
	 * 查询所有角色
	 * 
	 * @return
	 */
	List<SysRole> select();

}