package com.lanou.mapper;

import org.mybatis.spring.annotation.MapperScan;

import com.lanou.entity.SysRoleMenu;

@MapperScan
public interface SysRoleMenuMapper {
	/**
	 * 根据角色菜单id删除角色菜单信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_role_menu
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * 新增角色菜单信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_role_menu
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	int insert(SysRoleMenu record);

	/**
	 * 动态新增角色菜单信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_role_menu
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	int insertSelective(SysRoleMenu record);

	/**
	 * 根据角色菜单id查询角色菜单信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_role_menu
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	SysRoleMenu selectByPrimaryKey(Integer id);

	/**
	 * 动态修改角色菜单信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_role_menu
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	int updateByPrimaryKeySelective(SysRoleMenu record);

	/**
	 * 修改角色菜单信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_role_menu
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	int updateByPrimaryKey(SysRoleMenu record);
}