package com.lanou.mapper;

import java.util.Date;
import java.util.List;
import java.util.Map;

import org.mybatis.spring.annotation.MapperScan;

import com.lanou.bean.UserBean;
import com.lanou.entity.SysUser;

@MapperScan
public interface SysUserMapper {
	/**
	 * 根据用户id删除用户信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_user
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * 新增用户信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_user
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	int insert(SysUser record);

	/**
	 * 动态新增用户信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_user
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	int insertSelective(SysUser record);

	/**
	 * 根据用户id查询用户信息 根据用户id查询用户信息 This method was generated by MyBatis Generator.
	 * This method corresponds to the database table sys_user
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	SysUser selectByPrimaryKey(Integer id);

	/**
	 * 动态修改用户信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_user
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	int updateByPrimaryKeySelective(SysUser record);

	/**
	 * 修改用户信息 This method was generated by MyBatis Generator. This method
	 * corresponds to the database table sys_user
	 *
	 * @mbg.generated Tue Dec 26 10:20:04 CST 2017
	 */
	int updateByPrimaryKey(SysUser record);

	/**
	 * 根据用户名和密码查询用户信息
	 * 
	 * @param name
	 * 
	 * @param pwd
	 * @return
	 */
	SysUser selectUserByNameAndPwd(Map<String, Object> map);

	/**
	 * 总记录条数
	 * 
	 * @param map
	 * @return
	 */
	int selectPageCount(Map<String, Object> map);

	/**
	 * 负责分页查询用户信息
	 * 
	 * @param map
	 * @return
	 */
	List<UserBean> selectPageByUser(Map<String, Object> map);

}